import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { ChevronLeft, ChevronRight, ZoomIn } from 'lucide-react';
import { Dialog, DialogContent, DialogTrigger, } from '@/components/ui/dialog';
export default function ImageGallery({ images, title }) {
    const [currentIndex, setCurrentIndex] = useState(0);
    const nextImage = () => {
        setCurrentIndex((prev) => (prev + 1) % images.length);
    };
    const prevImage = () => {
        setCurrentIndex((prev) => (prev - 1 + images.length) % images.length);
    };
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "relative aspect-video rounded-xl overflow-hidden bg-gray-100", children: [_jsxs(Dialog, { children: [_jsx(DialogTrigger, { asChild: true, children: _jsxs("button", { className: "w-full h-full relative group", children: [_jsx("img", { src: images[currentIndex], alt: `${title} - Image ${currentIndex + 1}`, className: "w-full h-full object-cover cursor-zoom-in" }), _jsx("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center", children: _jsx(ZoomIn, { className: "h-10 w-10 text-white opacity-0 group-hover:opacity-100 transition-opacity" }) })] }) }), _jsx(DialogContent, { className: "max-w-5xl w-full p-0 bg-black/90 border-none", children: _jsxs("div", { className: "relative aspect-video", children: [_jsx("img", { src: images[currentIndex], alt: `${title} - Image ${currentIndex + 1}`, className: "w-full h-full object-contain" }), _jsx("button", { onClick: prevImage, className: "absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-colors", children: _jsx(ChevronLeft, { className: "h-6 w-6 text-white" }) }), _jsx("button", { onClick: nextImage, className: "absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-colors", children: _jsx(ChevronRight, { className: "h-6 w-6 text-white" }) }), _jsxs("div", { className: "absolute bottom-4 left-1/2 -translate-x-1/2 bg-black/60 text-white px-4 py-2 rounded-full text-sm", children: [currentIndex + 1, " / ", images.length] })] }) })] }), images.length > 1 && (_jsxs(_Fragment, { children: [_jsx("button", { onClick: prevImage, className: "absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/80 hover:bg-white rounded-full flex items-center justify-center shadow-lg transition-colors", children: _jsx(ChevronLeft, { className: "h-6 w-6 text-gray-700" }) }), _jsx("button", { onClick: nextImage, className: "absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/80 hover:bg-white rounded-full flex items-center justify-center shadow-lg transition-colors", children: _jsx(ChevronRight, { className: "h-6 w-6 text-gray-700" }) })] })), _jsxs("div", { className: "absolute top-4 right-4 bg-black/60 text-white px-3 py-1 rounded-full text-sm", children: [currentIndex + 1, " / ", images.length] })] }), images.length > 1 && (_jsx("div", { className: "flex space-x-2 overflow-x-auto pb-2", children: images.map((image, index) => (_jsx("button", { onClick: () => setCurrentIndex(index), className: `flex-shrink-0 w-20 h-16 rounded-lg overflow-hidden border-2 transition-colors ${index === currentIndex ? 'border-blue-600' : 'border-transparent hover:border-gray-300'}`, children: _jsx("img", { src: image, alt: `${title} thumbnail ${index + 1}`, className: "w-full h-full object-cover" }) }, index))) }))] }));
}
